package com.teamrocket.uttylermaps

import android.annotation.SuppressLint
import android.os.Bundle
import android.util.Log
import android.app.Activity
import androidx.activity.result.contract.ActivityResultContracts
import com.mappedin.models.Space
import androidx.appcompat.app.AppCompatActivity
import com.mappedin.MapView
import com.mappedin.models.AddLabelOptions
import com.mappedin.models.Doors
import com.mappedin.models.DoorsUpdateState
import com.mappedin.models.Floor
import com.mappedin.models.GeometryUpdateState
import com.mappedin.models.GetMapDataWithCredentialsOptions
import com.mappedin.models.LabelAppearance
import com.mappedin.models.MapDataType
import com.mappedin.models.Show3DMapOptions
import android.content.Intent
import android.os.Handler
import android.os.Looper
import com.mappedin.models.CameraAnimationOptions
import com.mappedin.models.CameraTarget
import com.mappedin.models.EasingFunction
import android.content.pm.PackageManager
import android.view.View
import androidx.appcompat.app.AppCompatDelegate
import androidx.core.view.WindowCompat
import com.mappedin.models.Coordinate
import com.indooratlas.android.sdk.IALocation
import com.indooratlas.android.sdk.IALocationListener
import com.indooratlas.android.sdk.IALocationManager
import com.indooratlas.android.sdk.IALocationRequest
import com.mappedin.models.AddMarkerOptions
import com.mappedin.models.CollisionRankingTier
import com.mappedin.models.Connection
import com.mappedin.models.Events
import com.mappedin.models.FloorUpdateState
import com.mappedin.models.FollowMode
import kotlin.onSuccess



/*
    parts  of the code in this project are adapted from
    Mappedin's android sdk documentation at https://developer.mappedin.com/android-sdk

    All dokka Kdot comments below are generated by Claude. Prompt: Add dokka kdoc comments
    to the class and each function
 */

/**
 * Main activity for the UT Tyler Maps application.
 *
 * This activity is responsible for rendering an interactive indoor map using the Mappedin SDK,
 * tracking the user's real-time indoor position via IndoorAtlas, and providing features such as
 * room search, turn-by-turn navigation, floor switching, and space highlighting.
 *
 * Implements [IALocationListener] to receive indoor location updates from IndoorAtlas.
 *
 * @see FloorManager for floor switching logic
 * @see BlueDotManager for user position indicator management
 * @see NavigationManager for route calculation and turn-by-turn guidance
 * @see UIBuilder for constructing the activity's UI programmatically
 */
class MapActivity : AppCompatActivity(), IALocationListener {
    private lateinit var mapView: MapView
    lateinit var ui: UIBuilder
    private var mapReady = false
    var allSpaces: List<Space> = emptyList()
    private var highlightedLabelSpace: Space? = null
    private var resetRunnable: Runnable? = null
    private val resetHandler = Handler(Looper.getMainLooper())
    private val labelMap = mutableMapOf<String, com.mappedin.models.Label>()

    // indoor atlas
    private lateinit var iaLocationManager: IALocationManager
    private var lastLocation: IALocation? = null
    private var hasPermissions = false
    var isFollowingUser = false
    private var blueDotFloorId: String? = null


    lateinit var floorManager: FloorManager
    private lateinit var blueDotManager: BlueDotManager
    private lateinit var navigationManager: NavigationManager


    private var isDark = false//dark mode flag

    private val prefs by lazy {
        androidx.preference.PreferenceManager.getDefaultSharedPreferences(this)
    }

    private val annotationMarkerMap = mutableMapOf<String, com.mappedin.models.Annotation>()

    /**
     * Activity result launcher for the [NavigationActivity].
     *
     * When the user selects an origin and/or destination room in the navigation screen,
     * this callback receives the result and initiates navigation. If an origin room is
     * provided, navigation is calculated from that space; otherwise, the user's current
     * IndoorAtlas location is used as the starting point.
     */
    private val navLauncher = registerForActivityResult(
        ActivityResultContracts.StartActivityForResult()
    ) { result ->
        if (result.resultCode == Activity.RESULT_OK) {
            val originRoom = result.data?.getStringExtra("origin_room")
            val destRoom = result.data?.getStringExtra("dest_room") ?: return@registerForActivityResult

            val dest = allSpaces.find { it.name == destRoom } ?: return@registerForActivityResult
            val accessible = prefs.getBoolean("accessible_routes", false)

            if (originRoom != null) {
                val origin = allSpaces.find { it.name == originRoom }
                if (origin != null) {
                    navigationManager.navigateFromSpace(origin, dest, accessible)
                }
            } else {
                val loc = lastLocation
                val floor = blueDotFloorId
                if (loc == null || floor == null) {
                    android.widget.Toast.makeText(this, "Waiting for location signal...", android.widget.Toast.LENGTH_SHORT).show()
                    return@registerForActivityResult
                }
                navigationManager.navigateTo(dest, loc.latitude, loc.longitude, floor, accessible)
            }
        }
    }

    /**
     * Called when the activity is first created.
     *
     * Performs initial setup including:
     * - Applying the user's theme preference (light, dark, or system default)
     * - Initializing the [MapView] and [UIBuilder]
     * - Configuring edge-to-edge display
     * - Registering a back-press handler for dismissing search, info panels, navigation, and filters
     * - Creating the [IALocationManager] and requesting location permissions
     * - Triggering the map data load via [loadMap]
     *
     * @param savedInstanceState the previously saved instance state, if any
     */
    override fun onCreate(savedInstanceState: Bundle?) {
        val prefs = androidx.preference.PreferenceManager.getDefaultSharedPreferences(this)
        when (prefs.getString("theme_preference", "system")) {
            "light" -> AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO)
            "dark" -> AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)
            else -> AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM)
        }
        super.onCreate(savedInstanceState)
        isDark = (resources.configuration.uiMode and
                android.content.res.Configuration.UI_MODE_NIGHT_MASK) ==
                android.content.res.Configuration.UI_MODE_NIGHT_YES

        title = "Display a Map"

        mapView = MapView(this)



        ui = UIBuilder(this, isDark, mapView)


        setContentView(ui.buildInitialLayout())

        // Enable edge to edge
        WindowCompat.setDecorFitsSystemWindows(window, false)
        window.navigationBarColor = android.graphics.Color.TRANSPARENT
        window.isNavigationBarContrastEnforced = false

        onBackPressedDispatcher.addCallback(this, object : androidx.activity.OnBackPressedCallback(true) {
            private var pressedOnce = false

            override fun handleOnBackPressed() {
                //close search
                if (ui.materialSearchView.isShowing) {
                    ui.dismissSearch()
                    return
                }

                // dismiss info panel
                if (navigationManager.isInfoPanelShowing()) {
                    navigationManager.dismissInfoPanel()
                    resetHighlightedLabel()
                    return
                }

                // stop navigation
                if (navigationManager.isNavigating) {
                    navigationManager.stopNavigation()
                    return
                }

                // clear filter
                if (ui.isFilterActive()) {
                    ui.clearFilter()
                    return
                }

                // double press to exit
                if (pressedOnce) {
                    finish()
                    return
                }
                pressedOnce = true
                android.widget.Toast.makeText(this@MapActivity, "Press again to exit", android.widget.Toast.LENGTH_SHORT).show()
                Handler(Looper.getMainLooper()).postDelayed({ pressedOnce = false }, 2000)
            }
        })

        iaLocationManager = IALocationManager.create(this)

        val permissions = mutableListOf(android.Manifest.permission.ACCESS_FINE_LOCATION)
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S) {
            permissions.add(android.Manifest.permission.BLUETOOTH_SCAN)
            permissions.add(android.Manifest.permission.BLUETOOTH_CONNECT)
        }
        requestPermissions(permissions.toTypedArray(), 0)

        loadMap()
    }

    /**
     * Toggles the camera follow mode for the user's blue dot location.
     *
     * If the user is not currently being followed, the camera switches to the user's floor
     * (if necessary) and begins tracking their position. The follow mode is set to
     * [FollowMode.POSITION_AND_PATH_DIRECTION] during active navigation, or
     * [FollowMode.POSITION_ONLY] otherwise.
     *
     * If follow mode is already active, it is disabled. The location button color in the UI
     * is updated to reflect the current state (blue when active, gray when inactive).
     *
     * Shows a toast if no location fix has been acquired yet.
     */
    private fun enableFollowMode() {
        if (lastLocation == null) {
            android.widget.Toast.makeText(this, "Waiting for location...", android.widget.Toast.LENGTH_SHORT).show()
            return
        }
        if (isFollowingUser) {
            mapView.blueDot.follow(mode = null)
            isFollowingUser = false
            ui.setLocationButtonColor("#657085")
        } else {

            val userFloor = floorManager.allFloors.find { it.id == blueDotFloorId }
            if (userFloor != null && floorManager.currentFloor?.id != userFloor.id) {
                floorManager.switchToFloor(userFloor)
                ui.highlightFloor(userFloor)
                syncBlueDotVisibility()
            }

            val mode = if (navigationManager.isNavigating)
                FollowMode.POSITION_AND_PATH_DIRECTION else FollowMode.POSITION_ONLY
            mapView.blueDot.follow(mode)
            isFollowingUser = true
            ui.setLocationButtonColor("#2563EB")

            // move camera to location
            moveToUserLocation()
        }
    }

    /**
     * Fetches map data from the Mappedin API using stored credentials.
     *
     * Constructs a [GetMapDataWithCredentialsOptions] using the API key, secret, and map ID
     * from [BuildConfig]. If the app is in dark mode, the alternate view ID `"Ptix"` is used.
     *
     * On success, the 3D map is rendered via [MapView.show3dMap], which then triggers
     * [onMapReady] once the map is fully loaded. Errors are logged to Logcat.
     */
    private fun loadMap() {
        val options = GetMapDataWithCredentialsOptions(
            key = BuildConfig.MAPPEDIN_KEY,
            secret = BuildConfig.MAPPEDIN_SECRET,
            mapId = BuildConfig.MAPPEDIN_MAP_ID,
            viewId = if (isDark) "Ptix" else null
        )

        mapView.getMapData(options) { result ->
            result.onSuccess {
                runOnUiThread {
                    mapView.view.post {
                        mapView.show3dMap(Show3DMapOptions()) { r ->
                            r.onSuccess { onMapReady() }
                            r.onFailure { Log.e("MapLoad", "show3dMap error: $it") }
                        }
                    }
                }
            }.onFailure {
                Log.e("Mappedin", "getMapData error: $it")
            }
        }
    }



    /**
     * Callback invoked when the Mappedin 3D map has finished rendering and is interactive.
     *
     * This method performs the following setup:
     * - Initializes [FloorManager], [BlueDotManager], and [NavigationManager]
     * - Registers a floor-change callback on [FloorManager] to toggle blue dot visibility
     * - Queries all [Space] objects from the map data, makes them interactive, and adds labels
     * - Removes the loading overlay and builds the control UI (location, navigation, settings, search)
     * - Enables the Mappedin search API
     * - Makes interior doors visible with styling
     * - Loads safety annotations and connection labels (stairs/elevators)
     * - Fetches all floors and builds the floor switcher UI
     * - Enables the blue dot for indoor positioning
     * - Registers click and touch listeners on the map for space selection and info panel display
     * - Pins a fake blue dot location on the first floor for testing purposes
     * - Listens for floor-change events to keep the floor switcher UI in sync
     */
    @SuppressLint("ClickableViewAccessibility")
    private fun onMapReady() {
        //setup the managers
        floorManager = FloorManager(mapView)
        blueDotManager = BlueDotManager(mapView)
        navigationManager = NavigationManager(this, mapView, ui.container, isDark)
        mapReady = true

        floorManager.onFloorChanged = { displayedFloor ->
            val userFloor = blueDotFloorId
            if (userFloor != null && userFloor != displayedFloor.id) {
                // viewing different floor , hide blue dot
                mapView.blueDot.disable()
            } else {
                // on user's floor , reenable blue dot
                blueDotManager.enable()
                // send position so it shows immediately
                val loc = lastLocation
                val floor = floorManager.allFloors.find { it.id == userFloor }
                if (loc != null && floor != null) {
                    blueDotManager.updatePosition(
                        loc.latitude, loc.longitude,
                        loc.accuracy.toDouble(), floor
                    )
                }
            }
        }
        mapView.mapData.getByType<Space>(MapDataType.SPACE) { result ->
            result.onSuccess { spaces ->
                allSpaces = spaces
                ui.allSpaces = spaces
                spaces.forEach { space ->
                    mapView.updateState(space, GeometryUpdateState(interactive = true))
                }
                addLabelsToSpaces(spaces) // add labels
            }
        }

        runOnUiThread {
            ui.loadingIndicator.visibility = View.GONE
            ui.container.findViewWithTag<View>("loadingOverlay")?.let {
                ui.container.removeView(it)
            }
            ui.buildControls(
                onLocationClick = { enableFollowMode() },
                onNavClick = {
                    val intent = Intent(this, NavigationActivity::class.java)
                    val roomNames = allSpaces.map { it.name }.filter { it.isNotBlank() }.distinct().sorted()
                    intent.putStringArrayListExtra("room_names", ArrayList(roomNames))
                    navLauncher.launch(intent)
                },
                onSettingsClick = { startActivity(Intent(this, SettingsActivity::class.java)) },
                onSearchSubmit = { query -> navigateToRoom(query) },
                onSearchItemClick = { room -> navigateToRoom(room) },

                )
        }
        mapView.mapData.search.enable { result ->
            result.onSuccess {
                Log.d("Search", "Search enabled")
            }
        }//handles clicks

        //make doors visible
        mapView.updateState(
            Doors.INTERIOR,
            DoorsUpdateState(
                visible = true,
                color = if(isDark) "black" else "grey",
                topColor = "brown",
                opacity = 0.5
            ),
        )


        //add safety annotations
        val showAnnotations = prefs.getBoolean("show_safety_annotations", true)
        //loadAnnotations()
        val stairsSvg = """<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M19 3h-4v4h-4v4H7v4H3v6h4v-4h4v-4h4V9h4V3z"/></svg>"""

        val elevatorSvg = """<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M7 2l5 5H2zm10 0l5 5h-10zM7 22l5-5H2zm10 0l5-5h-10z"/></svg>"""


        addConnectionLabels()
        loadAnnotations()

        //load floors
        mapView.mapData.getByType<Floor>(MapDataType.FLOOR) { result ->
            result.onSuccess { floors ->
                floorManager.setFloors(floors)
                runOnUiThread {
                    ui.buildFloorSwitcher(floors) { floor ->
                        floorManager.switchToFloor(floor)
                        syncBlueDotVisibility()
                    }
                    floorManager.currentFloor?.let { ui.highlightFloor(it) }
                }
            }

            result.onSuccess { floors ->
                for (floor in floors) {
                    mapView.updateState(
                        floor,
                        FloorUpdateState(
                            markers = FloorUpdateState.Markers(enabled = true)
                        )
                    )
                }
            }
        }
        //enable the blue dot after all map loads
        blueDotManager.enable()

        // listen for space taps
        mapView.on(Events.Click) { payload -> handleMapClick(payload) }

        //to track tapping away
        mapView.view.setOnTouchListener { v, event ->
            // block taps in bottom-left watermark area
            if (event.action == android.view.MotionEvent.ACTION_DOWN ||
                event.action == android.view.MotionEvent.ACTION_UP) {
                val density = resources.displayMetrics.density
                val blockWidth = 220 * density
                val blockHeight = 90 * density
                val inBottomLeft =
                    event.x <= blockWidth &&
                            event.y >= (v.height - blockHeight)

                if (inBottomLeft) {
                    Log.d("WatermarkBlock", "Blocked watermark tap")
                    return@setOnTouchListener true
                }
            }
            if (isFollowingUser) {
                isFollowingUser = false
                runOnUiThread { ui.setLocationButtonColor("#657085") }
            }
            ui.dismissSearch()

            if (!ui.isFilterActive()) {
                resetRunnable?.let { resetHandler.removeCallbacks(it) }
                resetRunnable = Runnable {
                    resetHighlightedLabel()
                    navigationManager.dismissInfoPanel()
                }
                resetHandler.postDelayed(resetRunnable!!, 300)
            }
            false
        }

        //listen for floor changes
        mapView.on(Events.FloorChange) { payload ->
            val newFloor = payload?.floor ?: return@on
            // Update FloorManager's tracked floor without calling setFloor again
            floorManager.currentFloor = floorManager.allFloors.find{it.id == newFloor.id}

            runOnUiThread {
                ui.highlightFloor((floorManager.currentFloor!!))
                syncBlueDotVisibility()
            }
        }


    }//onmapready

    /** SVG icon used for restroom labels on the map. */
    private val restroomIcon = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="white"><path d="M5.5 22v-7.5H4V9c0-1.1.9-2 2-2h3c1.1 0 2 .9 2 2v5.5H9.5V22h-4zm12.5 0v-6h3l-2.54-7.63C18.18 7.55 17.42 7 16.56 7h-.12c-.86 0-1.63.55-1.9 1.37L12 16h3v6h3zM7.5 6c1.11 0 2-.89 2-2s-.89-2-2-2-2 .89-2 2 .89 2 2 2zm9 0c1.11 0 2-.89 2-2s-.89-2-2-2-2 .89-2 2 .89 2 2 2z"/></svg>"""

    /** SVG icon used for elevator labels on the map. */
    private val elevatorIcon = """<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 8H17C17.5523 8 18 8.44772 18 9V19C18 19.5523 17.5523 20 17 20H12M12 8H7C6.44772 8 6 8.44772 6 9V19C6 19.5523 6.44772 20 7 20H12M12 8V20M7.5 4.5L9 3L10.5 4.5M13.5 3L15 4.5L16.5 3" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none"/></svg>"""

    /** SVG icon used for staircase labels on the map. */
    private val stairsIcon = """<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="white"><path d="M19 3h-4v4h-4v4H7v4H3v6h4v-4h4v-4h4V9h4V3z"/></svg>"""

    /**
     * Adds interactive text labels (and icon badges for amenities) to all named spaces on the map.
     *
     * For each [Space] in the provided list:
     * - Spaces with names containing "Restroom", "Elevator", or "Stair" receive a colored icon
     *   badge with a higher collision ranking so they remain visible at lower zoom levels.
     * - All other named spaces receive a default text-only label.
     *
     * Successfully created labels are stored in [labelMap] keyed by space name for later reference.
     *
     * @param spaces the list of [Space] objects to label on the map
     */
    private fun addLabelsToSpaces(spaces: List<Space>) {
        for (space in spaces) {
            if (space.name.isEmpty()) continue

            val isAmenity = space.name.contains("Restroom", true) ||
                    space.name.contains("Elevator", true) ||
                    space.name.contains("Stair", true)

            val icon = when {
                space.name.contains("Restroom", true) -> restroomIcon
                space.name.contains("Elevator", true) -> elevatorIcon
                space.name.contains("Stair", true) -> stairsIcon
                else -> null
            }
            val bgColor = when {
                space.name.contains("Restroom", true) -> "#4e7498"
                space.name.contains("Elevator", true) -> "#15803D"
                space.name.contains("Stair", true) -> "#15803D"
                else -> null
            }

            val options = if (isAmenity && icon != null) {
                AddLabelOptions(
                    labelAppearance = LabelAppearance(icon = icon, color = bgColor, iconVisibleAtZoomLevel = .7),
                    interactive = true,
                    rank = CollisionRankingTier.HIGH
                )
            } else {
                AddLabelOptions(labelAppearance = LabelAppearance(), interactive = true)
            }

            mapView.labels.add(target = space, text = space.name, options = options) { result ->
                result.onSuccess { label -> if (label != null) labelMap[space.name] = label }
            }
        }
    }

    /**
     * Adds icon labels to all map connections (stairs and elevators) at their coordinate positions.
     *
     * Iterates over all [Connection] objects in the map data. Each connection's coordinates
     * receive an icon label: a stairs icon for [Connection.ConnectionType.STAIRS] and an
     * elevator arrow icon for all other connection types. Labels are styled with a green
     * background and medium collision ranking.
     */
    private fun addConnectionLabels() {
        mapView.mapData.getByType<Connection>(MapDataType.CONNECTION) { result ->
            result.onSuccess { connections ->
                for (connection in connections) {
                    val icon = if (connection.type == Connection.ConnectionType.STAIRS) stairsIcon
                    else """<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="white"><path d="M7 2l5 5H2zm10 0l5 5h-10zM7 22l5-5H2zm10 0l5-5h-10z"/></svg>"""

                    connection.coordinates.forEach { coordinate ->
                        mapView.labels.add(
                            target = coordinate, text = "",
                            options = AddLabelOptions(
                                labelAppearance = LabelAppearance(color = "#15803D", icon = icon),
                                rank = CollisionRankingTier.MEDIUM
                            )
                        )
                    }
                }
            }
        }
    }

    /**
     * Loads and displays safety annotation markers on the map.
     *
     * First removes all existing markers, then checks the user's preference for
     * `show_safety_annotations`. If enabled, queries all [com.mappedin.models.Annotation]
     * objects from the map data and places interactive markers at each annotation's coordinate.
     *
     * If an annotation has an icon URL, it is rendered as an `<img>` element; otherwise,
     * a red circle with a warning symbol is displayed as a fallback.
     */
    private fun loadAnnotations() {
        // Remove existing ones first
        mapView.markers.removeAll {  }


        val showAnnotations = prefs.getBoolean("show_safety_annotations", true)
        if (!showAnnotations) return

        mapView.mapData.getByType<com.mappedin.models.Annotation>(MapDataType.ANNOTATION) { result ->
            result.onSuccess { annotations ->
                for (annotation in annotations) {
                    val coord = annotation.coordinate
                    val iconUrl = annotation.icon?.url

                    val iconHtml = if (iconUrl != null) {
                        """<img src="$iconUrl" width="28" height="28" style="display:block;"/>"""
                    } else {
                        """<div style="background:red;color:white;border-radius:50%;
                        width:28px;height:28px;display:flex;align-items:center;
                        justify-content:center;font-size:14px;">⚠</div>"""
                    }

                    mapView.markers.add(
                        target = coord,
                        html = iconHtml,
                        options = com.mappedin.models.AddMarkerOptions(
                            interactive = AddMarkerOptions.Interactive.True,
                            rank = AddMarkerOptions.Rank.Tier(CollisionRankingTier.MEDIUM)
                        )
                    )
                }
            }
        }
    }

    /**
     * Places the blue dot at a hardcoded latitude/longitude for testing purposes.
     *
     * Updates the [BlueDotManager] position and stores a synthetic [IALocation] in
     * [lastLocation] so that navigation and follow-mode features work without a real
     * IndoorAtlas signal.
     *
     * @param lat the latitude to place the blue dot at
     * @param lon the longitude to place the blue dot at
     * @param floor the [Floor] to associate with the fake location; defaults to [FloorManager.currentFloor]
     */
    private fun setFakeLocation(lat: Double, lon: Double, floor: Floor? = null) {
        val targetFloor = floor ?: floorManager.currentFloor ?: return
        blueDotFloorId = targetFloor.id  // track it here too

        blueDotManager.updatePosition(lat, lon, 3.0, targetFloor)
        lastLocation = IALocation.from(android.location.Location("fake").apply {
            latitude = lat
            longitude = lon
            accuracy = 3.0f
        })
    }

    /**
     * Resets the previously highlighted space to its default visual state.
     *
     * If a space was highlighted (e.g., from a search result or tap), its geometry color
     * and opacity are restored to their initial values and the [highlightedLabelSpace]
     * reference is cleared.
     */
    private fun resetHighlightedLabel() {
        highlightedLabelSpace?.let { prev ->
            mapView.updateState(prev, GeometryUpdateState(
                color = "initial",
                opacity = 1.0
            ))
        }
        highlightedLabelSpace = null
    }

    /**
     * Animates the map camera to center on the user's current indoor location.
     *
     * Uses the most recent [IALocation] stored in [lastLocation] to target the camera
     * at zoom level 20 with a top-down pitch. If no location has been received yet,
     * an error is logged and the method returns without action.
     */
    private fun moveToUserLocation() {
        val location = lastLocation

        if (location == null) {
            Log.e("Location", "No location yet")
            return
        }

        mapView.camera.animateTo(
            CameraTarget(
                center = Coordinate(location.latitude, location.longitude),
                zoomLevel = 20.0,
                pitch = 0.0
            ),
            CameraAnimationOptions(
                duration = 1000,
                easing = EasingFunction.EASE_OUT
            )
        )
    }

    /**
     * Navigates the map camera to a specific room by name.
     *
     * Adds the room name to the search history, locates the matching [Space], switches
     * to its floor if necessary, highlights the space geometry in burnt orange (`#BF5700`),
     * and smoothly animates the camera to center on the room.
     *
     * If no space matching [roomName] is found, an error is logged and the method returns.
     *
     * @param roomName the display name of the room to navigate to (case-insensitive match)
     */
    private fun navigateToRoom(roomName: String) {
        ui.searchHistory.addSearch(roomName)
        val space = allSpaces.find {
            it.name.equals(roomName, ignoreCase = true)
        }

        if (space == null) {
            Log.e("Mappedin", "Could not find space: $roomName")
            return
        }

        //switch to correct floor

        if (space.floor != null && floorManager.currentFloor?.id != space.floor) {
            // Find the matching Floor object from your FloorManager
            val targetFloor = floorManager.allFloors.find { it.id == space.floor }
            if (targetFloor != null) {
                floorManager.switchToFloor(targetFloor)
                ui.highlightFloor(targetFloor)
            }
        }

        //clear old highlight before setting new one
        resetHighlightedLabel()
        mapView.updateState(space, GeometryUpdateState(
            color = "#BF5700",
            opacity = 0.6
        ))
        highlightedLabelSpace = space

        //zoom camera to the room
        mapView.camera.animateTo(
            CameraTarget(
                center = space.center,
                zoomLevel = 20.0,
                pitch = 0.0
            ),
            CameraAnimationOptions(
                duration = 1000,
                easing = EasingFunction.EASE_OUT
            )
        )
    }

    /**
     * Removes all labels from the map and re-adds them for every space and connection.
     *
     * This is useful after a theme change or filter reset to ensure labels are rendered
     * with the correct styling and visibility.
     */
    fun reAddAllLabels() {
        mapView.labels.removeAll()
        addLabelsToSpaces(allSpaces)
        addConnectionLabels()
    }

    /**
     * Handles tap events on the map surface.
     *
     * Determines what was tapped from the [com.mappedin.models.ClickPayload]:
     * - If an annotation marker was tapped, displays a toast with the annotation's type and group.
     * - If a filter is active, only shows the info panel for tapped spaces without clearing the filter.
     * - Otherwise, highlights the tapped space and displays its info panel. Tapping empty
     *   space dismisses the info panel and resets any highlight.
     *
     * @param payload the click payload from the Mappedin SDK containing tapped spaces, labels, and markers
     */
    private fun handleMapClick(payload: com.mappedin.models.ClickPayload?) {
        resetRunnable?.let { resetHandler.removeCallbacks(it) }

        val clickedSpace = payload?.spaces?.firstOrNull()
            ?: payload?.labels?.firstOrNull()?.let { label ->
                allSpaces.find { it.name == label.text }
            }

        // if user taps an annotation marker
        payload?.markers?.firstOrNull()?.let { marker ->
            annotationMarkerMap[marker.id]?.let { annotation ->
                runOnUiThread {
                    android.widget.Toast.makeText(this, "${annotation.type} (${annotation.group})", android.widget.Toast.LENGTH_SHORT).show()
                }
                return
            }
        }

        if (ui.isFilterActive()) {
            if (clickedSpace != null && clickedSpace.name.isNotBlank()) {
                runOnUiThread { showInfoPanelForSpace(clickedSpace) }
            }
            return
        }

        resetHighlightedLabel()
        if (clickedSpace == null) {
            runOnUiThread { navigationManager.dismissInfoPanel() }
            return
        }
        if (clickedSpace.name.isNotBlank()) {
            //highlight the room and show info panel
            highlightSpace(clickedSpace)
            runOnUiThread { showInfoPanelForSpace(clickedSpace) }
        }
    }

    /**
     * Applies a burnt-orange highlight to the given space's geometry on the map.
     *
     * Cancels any pending reset runnable, updates the space's color to `#BF5700` at
     * 60% opacity, and stores the space reference in [highlightedLabelSpace] so it
     * can be reset later.
     *
     * @param space the [Space] to visually highlight
     */
    private fun highlightSpace(space: Space) {
        resetRunnable?.let { resetHandler.removeCallbacks(it) }
        mapView.updateState(space, GeometryUpdateState(color = "#BF5700", opacity = 0.6))
        highlightedLabelSpace = space
    }

    /**
     * Displays the info panel for a given space with optional directions functionality.
     *
     * Delegates to [NavigationManager.showSpaceInfoPanel] to render the bottom sheet.
     * If the user has a valid location fix, the "Directions" button will initiate
     * turn-by-turn navigation from the user's current position to the selected space,
     * respecting the user's accessible-routes preference.
     *
     * @param space the [Space] to display information about
     */
    private fun showInfoPanelForSpace(space: Space) {
        navigationManager.showSpaceInfoPanel(
            space = space,
            hasLocation = lastLocation != null,
            onDirections = {
                val loc = lastLocation ?: return@showSpaceInfoPanel
                val floor = blueDotFloorId ?: return@showSpaceInfoPanel
                val accessible = prefs.getBoolean("accessible_routes", false)
                syncBlueDotVisibility()
                navigationManager.navigateTo(space, loc.latitude, loc.longitude, floor, accessible)
                syncBlueDotVisibility()
            }
        )
    }

    // --- IndoorAtlas lifecycle callbacks ---

    /**
     * Called when the activity resumes.
     *
     * Re-registers for IndoorAtlas location updates if permissions have been granted,
     * and reloads safety annotations if the map is ready (to reflect any preference
     * changes made in [SettingsActivity]).
     */
    override fun onResume() {
        super.onResume()
        if(hasPermissions) {
            iaLocationManager.requestLocationUpdates(
                IALocationRequest.create(),
                this
            )
        }
        if (mapReady) {
            loadAnnotations()
        }
    }

    /**
     * Called when the activity pauses.
     *
     * Removes IndoorAtlas location update listeners to conserve battery and
     * prevent updates while the activity is not visible.
     */
    override fun onPause() {
        iaLocationManager.removeLocationUpdates(this)
        super.onPause()
    }

    /**
     * Called when the activity is destroyed.
     *
     * Releases all IndoorAtlas resources by destroying the [IALocationManager] instance.
     */
    override fun onDestroy() {
        iaLocationManager.destroy()
        super.onDestroy()
    }

    /**
     * Handles the result of the runtime permission request.
     *
     * If all requested permissions (location, and optionally Bluetooth on Android 12+)
     * are granted, sets [hasPermissions] to `true` and immediately begins requesting
     * IndoorAtlas location updates.
     *
     * @param requestCode the request code passed to [requestPermissions]
     * @param permissions the requested permissions
     * @param grantResults the grant results for each permission
     */
    override fun onRequestPermissionsResult(
        requestCode: Int,
        permissions: Array<out String>,
        grantResults: IntArray
    ) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        if(requestCode == 0 && grantResults.all { it == PackageManager.PERMISSION_GRANTED }) {
            hasPermissions = true
            iaLocationManager.requestLocationUpdates(
                IALocationRequest.create(),
                this
            )
        }
    }

    /**
     * Called by IndoorAtlas when a new indoor location fix is available.
     *
     * This method:
     * 1. Stores the latest [IALocation] in [lastLocation].
     * 2. Maps the IndoorAtlas floor level to a Mappedin [Floor] via [FloorManager.findFloorForLevel].
     * 3. Tracks the user's current floor in [blueDotFloorId].
     * 4. Optionally auto-switches the displayed floor if the `auto_floor_switch` preference is enabled.
     * 5. Updates the [BlueDotManager] with the new position.
     * 6. If navigation is active, updates the navigation path via [NavigationManager.updateNavigationPath].
     *
     * If the map is not yet ready or no matching floor is found, the update is skipped.
     *
     * @param location the new [IALocation] from IndoorAtlas
     */
    override fun onLocationChanged(location: IALocation) {

        lastLocation = location

        if (!mapReady) {
            Log.d("BlueDot", "Map not ready yet, skipping location update")
            return
        }

        val mappedFloor = floorManager.findFloorForLevel(location.floorLevel) ?: return
        blueDotFloorId = mappedFloor.id  // track actual user floor
        if (mappedFloor == null) {
            Log.w("BlueDot", "No Mappedin floor found for IA floorLevel=${location.floorLevel}")
            return
        }

        Log.d(
            "BlueDot",
            "IA floorLevel=${location.floorLevel}, mappedFloor=${mappedFloor.name}"
        )
        //if auto floor switch is enabled, switch floors
        val autoSwitch = prefs.getBoolean("auto_floor_switch", true)
        if (autoSwitch && floorManager.currentFloor?.id != mappedFloor.id) {
            floorManager.switchToFloor(mappedFloor)
            runOnUiThread { ui.highlightFloor(mappedFloor) }
        }
        runOnUiThread {
            ui.highlightFloor(mappedFloor)
        }
        syncBlueDotVisibility()

        blueDotManager.updatePosition(
            lat = location.latitude,
            lon = location.longitude,
            accuracy = location.accuracy.toDouble(),
            floor = mappedFloor
        )
        if (navigationManager.isNavigating) {
            navigationManager.updateNavigationPath(
                location.latitude, location.longitude, mappedFloor.id
            )
        }

    }

    /**
     * Synchronizes the blue dot visibility based on the user's actual floor versus
     * the currently displayed floor.
     *
     * If the user is on a different floor than what is currently being viewed, the
     * blue dot is hidden. When the user returns to (or the map switches to) their
     * actual floor, the blue dot is re-enabled and its position is immediately updated.
     */
    fun syncBlueDotVisibility() {
        val userFloor = blueDotFloorId ?: return
        val displayedFloor = floorManager.currentFloor?.id ?: return

        if (userFloor != displayedFloor) {
            mapView.blueDot.disable()
        } else {
            blueDotManager.enable()
            val loc = lastLocation
            val floor = floorManager.allFloors.find { it.id == userFloor }
            if (loc != null && floor != null) {
                blueDotManager.updatePosition(loc.latitude, loc.longitude, loc.accuracy.toDouble(), floor)
            }
        }
    }

    /**
     * Called when the IndoorAtlas positioning service status changes.
     *
     * Currently a no-op; required by the [IALocationListener] interface.
     *
     * @param provider the name of the location provider
     * @param status the new status code
     * @param extras optional extra information about the status change
     */
    override fun onStatusChanged(provider: String?, status: Int, extras: Bundle?) {
    }

}