package com.teamrocket.uttylermaps
//All dokka Kdot comments below are generated by Claude. Prompt: Add dokka kdoc comments
//    to the class and each function
import android.R
import android.util.Log
import android.view.Gravity
import android.view.View
import android.view.ViewGroup
import android.widget.Button
import android.widget.FrameLayout
import android.widget.LinearLayout
import android.widget.ListView
import android.widget.TextView
import androidx.core.graphics.toColorInt
import com.mappedin.MapView
import com.mappedin.models.AddMarkerOptions
import com.mappedin.models.Coordinate
import com.mappedin.models.Directions
import com.mappedin.models.NavigationTarget
import com.mappedin.models.PathSectionHighlightOptions
import com.mappedin.models.Space
import com.mappedin.models.NavigationOptions
import com.mappedin.models.AddPathOptions
import com.mappedin.models.CollisionRankingTier
import com.mappedin.models.GetDirectionsOptions

/**
 * Manages indoor navigation, route calculation, and navigation UI panels.
 *
 * This class is responsible for calculating directions between spaces (or from the user's
 * current coordinate to a space), rendering navigation paths on the map, displaying
 * turn-by-turn instruction markers, and managing the various bottom-sheet UI panels
 * (info panel, route plan panel, and active navigation panel).
 *
 * Supports both coordinate-based navigation (from the user's live IndoorAtlas position)
 * and space-to-space navigation (when the user selects an origin room). Accessible route
 * options are forwarded to the Mappedin directions API when enabled.
 *
 * @property activity the parent [MapActivity] used for UI context and access to shared state
 * @property mapView the [MapView] instance used to draw paths and markers
 * @property container the root [FrameLayout] to which navigation panels are added
 * @property isDark whether the app is currently in dark mode, used for panel styling
 * @see MapActivity.navLauncher for how navigation is triggered from the navigation screen
 */
class NavigationManager(
    private val activity: MapActivity,
    private val mapView: MapView,
    private val container: FrameLayout,
    private val isDark: Boolean,

    ) {
    private var infoPanel: LinearLayout? = null
    private var navigationPanel: LinearLayout? = null
    private var activeDestination: Space? = null
    private var navigationPlanPanel: LinearLayout? = null
    private var currentDirections: Directions? = null
    private var isRerouting = false
    private var activeFloorId: String? = null
    /** Whether turn-by-turn navigation is currently active. */
    var isNavigating = false
        private set
    private var selectedOrigin: Space? = null // null = user location
    private var selectedDestination: Space? = null
    private var activeField: String = "destination" // which field is being edited
    private var useAccessible = false
    private val bgColor get() = if (isDark) "#1E1E1E".toColorInt() else android.graphics.Color.WHITE
    private val textColor get() = if (isDark) android.graphics.Color.WHITE else android.graphics.Color.BLACK

    private val navOptions = NavigationOptions(
        pathOptions = AddPathOptions(
            color = "#BF5700",
            accentColor = "#002F6C" ,
            displayArrowsOnPath = true,
            animateDrawing = true,
            animateArrowsOnPath =  true,

        ),
        createMarkers = NavigationOptions.CreateMarkers.withCustomMarkers(
            departure = NavigationOptions.CreateMarkers.CreateMarkerValue.CustomMarker(
                template = """<div style="width:1px;height:1px;opacity:0;"></div>"""
            )
        )
    )

    /**
     * Displays a bottom-sheet info panel for a tapped space.
     *
     * Shows the space name and, if the user has a location fix, a "Directions" button
     * that triggers navigation to the space. A "Close" button dismisses the panel.
     *
     * @param space the [Space] to display information about
     * @param hasLocation whether the user currently has a valid indoor location fix
     * @param onDirections callback invoked when the user taps the "Directions" button
     */
    fun showSpaceInfoPanel(space: Space, hasLocation: Boolean, onDirections: () -> Unit) {
        dismissInfoPanel()
        dismissNavigationPanel()

        infoPanel = LinearLayout(activity).apply {
            orientation = LinearLayout.VERTICAL
            setPadding(48, 36, 48, 36)
            elevation = 24f
            background = android.graphics.drawable.GradientDrawable().apply {
                cornerRadii = floatArrayOf(32f, 32f, 32f, 32f, 0f, 0f, 0f, 0f)
                setColor(bgColor)
            }

            addView(TextView(activity).apply {
                text = space.name
                setTextColor(this@NavigationManager.textColor)
                textSize = 20f
                setTypeface(null, android.graphics.Typeface.BOLD)
            })

            if (hasLocation) {
                addView(Button(activity).apply {
                    text = "Directions"
                    setTextColor(android.graphics.Color.WHITE)
                    isAllCaps = false
                    background = android.graphics.drawable.GradientDrawable().apply {
                        cornerRadius = 24f
                        setColor("#2563EB".toColorInt())
                    }
                    layoutParams = LinearLayout.LayoutParams(
                        ViewGroup.LayoutParams.MATCH_PARENT,
                        ViewGroup.LayoutParams.WRAP_CONTENT
                    ).apply { topMargin = 24 }
                    setOnClickListener { onDirections() }
                })
            }

            addView(Button(activity).apply {
                text = "Close"
                isAllCaps = false
                setTextColor(this@NavigationManager.textColor)
                setBackgroundColor(android.graphics.Color.TRANSPARENT)
                layoutParams = LinearLayout.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.WRAP_CONTENT
                ).apply {
                    topMargin = 8
                    bottomMargin = 120
                }
                setOnClickListener { dismissInfoPanel() }
            })
        }

        val params = FrameLayout.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT,
            ViewGroup.LayoutParams.WRAP_CONTENT
        ).apply { gravity = Gravity.BOTTOM }

        container.addView(infoPanel, params)
    }

    /**
     * Removes the space info panel from the UI if it is currently showing.
     */
    fun dismissInfoPanel() {
        infoPanel?.let { container.removeView(it) }
        infoPanel = null
    }

    /**
     * Builds and displays the route plan panel showing distance, estimated walk time,
     * origin/destination fields, and a "Start" button.
     *
     * This panel is shown after directions have been calculated but before the user
     * commits to starting live navigation. It includes a swap button to reverse
     * origin and destination.
     *
     * @param destination the target [Space] for navigation
     * @param directions the calculated [Directions] containing the route
     * @param userLat the user's current latitude
     * @param userLon the user's current longitude
     * @param floorId the Mappedin floor ID of the user's current floor
     * @param accessible whether accessible routing was requested
     */
    private fun buildPlanPanel(
        destination: Space,
        directions: Directions,
        userLat: Double,
        userLon: Double,
        floorId: String,
        accessible: Boolean
    ) {
        val distanceText = if (directions.distance < 1000)
            "${directions.distance.toInt()} m"
        else
            "${"%.1f".format(directions.distance / 1000)} km"

        val walkSeconds = (directions.distance / 1.4).toInt()
        val timeText = if (walkSeconds < 60) "$walkSeconds sec"
        else "${walkSeconds / 60} min"

        val originLabel = if (selectedOrigin != null) selectedOrigin!!.name else "Your location"

        navigationPlanPanel = LinearLayout(activity).apply {
            orientation = LinearLayout.VERTICAL
            setPadding(0, 0, 0, 0)
            elevation = 24f
            background = android.graphics.drawable.GradientDrawable().apply {
                cornerRadii = floatArrayOf(32f, 32f, 32f, 32f, 0f, 0f, 0f, 0f)
                setColor(bgColor)
            }

            // Fields row with dots + inputs + swap
            val fieldsRow = LinearLayout(activity).apply {
                orientation = LinearLayout.HORIZONTAL
                gravity = Gravity.CENTER_VERTICAL
                setPadding(24, 32, 16, 16)

                // Dots column
                addView(buildDotsColumn())

                // Text fields column
                val inputsColumn = LinearLayout(activity).apply {
                    orientation = LinearLayout.VERTICAL
                    layoutParams = LinearLayout.LayoutParams(0, ViewGroup.LayoutParams.WRAP_CONTENT, 1f)
                }

                val inputBg = if (isDark) "#303134".toColorInt() else "#F1F3F4".toColorInt()
                val inputText = if (isDark) "#E8EAED".toColorInt() else "#202124".toColorInt()

                val originField = TextView(activity).apply {
                    text = originLabel
                    textSize = 15f
                    setTextColor(inputText)
                    background = android.graphics.drawable.GradientDrawable().apply {
                        cornerRadius = 24f
                        setColor(inputBg)
                    }
                    setPadding(36, 20, 36, 20)
                    layoutParams = LinearLayout.LayoutParams(
                        ViewGroup.LayoutParams.MATCH_PARENT,
                        ViewGroup.LayoutParams.WRAP_CONTENT
                    )
                }
                inputsColumn.addView(originField)

                inputsColumn.addView(android.view.View(activity).apply {
                    layoutParams = LinearLayout.LayoutParams(
                        ViewGroup.LayoutParams.MATCH_PARENT, 12
                    )
                })

                val destField = TextView(activity).apply {
                    text = destination.name
                    textSize = 15f
                    setTextColor(inputText)
                    background = android.graphics.drawable.GradientDrawable().apply {
                        cornerRadius = 24f
                        setColor(inputBg)
                    }
                    setPadding(36, 20, 36, 20)
                    layoutParams = LinearLayout.LayoutParams(
                        ViewGroup.LayoutParams.MATCH_PARENT,
                        ViewGroup.LayoutParams.WRAP_CONTENT
                    )
                }
                inputsColumn.addView(destField)

                addView(inputsColumn)

                // Swap button
                addView(Button(activity).apply {
                    text = "⇅"
                    textSize = 20f
                    setTextColor(this@NavigationManager.textColor)
                    setBackgroundColor(android.graphics.Color.TRANSPARENT)
                    layoutParams = LinearLayout.LayoutParams(
                        ViewGroup.LayoutParams.WRAP_CONTENT,
                        ViewGroup.LayoutParams.MATCH_PARENT
                    ).apply { marginStart = 8 }
                    setOnClickListener {
                        val temp = originField.text
                        originField.text = destField.text
                        destField.text = temp

                        val tempSpace = selectedOrigin
                        selectedOrigin = selectedDestination
                        selectedDestination = tempSpace
                    }
                })
            }
            addView(fieldsRow)

            // Divider
            addView(android.view.View(activity).apply {
                layoutParams = LinearLayout.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT, 2
                ).apply {
                    marginStart = 24
                    marginEnd = 24
                }
                setBackgroundColor(if (isDark) "#3C4043".toColorInt() else "#E0E0E0".toColorInt())
            })

            // Distance and time row
            addView(LinearLayout(activity).apply {
                orientation = LinearLayout.HORIZONTAL
                gravity = Gravity.CENTER_VERTICAL
                setPadding(36, 20, 36, 8)

                addView(TextView(activity).apply {
                    text = distanceText
                    textSize = 22f
                    setTextColor(this@NavigationManager.textColor)
                    setTypeface(null, android.graphics.Typeface.BOLD)
                })

                addView(TextView(activity).apply {
                    text = "  ·  "
                    textSize = 18f
                    setTextColor(if (isDark) "#9AA0A6".toColorInt() else "#5F6368".toColorInt())
                })

                addView(TextView(activity).apply {
                    text = "$timeText walk"
                    textSize = 18f
                    setTextColor(if (isDark) "#9AA0A6".toColorInt() else "#5F6368".toColorInt())
                })
            })

            // Start button
            addView(Button(activity).apply {
                text = "Start"
                isAllCaps = false
                textSize = 16f
                setTextColor(android.graphics.Color.WHITE)
                setTypeface(null, android.graphics.Typeface.BOLD)
                background = android.graphics.drawable.GradientDrawable().apply {
                    cornerRadius = 28f
                    setColor("#2563EB".toColorInt())
                }
                layoutParams = LinearLayout.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.WRAP_CONTENT
                ).apply {
                    topMargin = 16
                    marginStart = 24
                    marginEnd = 24
                }
                setPadding(0, 28, 0, 28)
                setOnClickListener {
                    dismissPlanPanel()
                    navigateTo(destination, userLat, userLon, floorId, accessible)
                }
            })

            // Close button
            addView(Button(activity).apply {
                text = "Close"
                isAllCaps = false
                setTextColor(this@NavigationManager.textColor)
                setBackgroundColor(android.graphics.Color.TRANSPARENT)
                layoutParams = LinearLayout.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.WRAP_CONTENT
                ).apply {
                    topMargin = 4
                    bottomMargin = 8
                }
                setOnClickListener { dismissPlanPanel() }
            })
        }

        val params = FrameLayout.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT,
            ViewGroup.LayoutParams.WRAP_CONTENT
        ).apply {
            gravity = Gravity.BOTTOM
            bottomMargin = 180
        }
        container.addView(navigationPlanPanel, params)
    }

    /**
     * Builds the vertical dots column used in the route plan panel to visually
     * connect the origin (green dot) and destination (blue dot) fields.
     *
     * @return a [LinearLayout] containing the origin dot, connecting line, and destination dot
     */
    private fun buildDotsColumn(): LinearLayout {
        return LinearLayout(activity).apply {
            orientation = LinearLayout.VERTICAL
            gravity = Gravity.CENTER_HORIZONTAL
            layoutParams = LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.WRAP_CONTENT,
                ViewGroup.LayoutParams.MATCH_PARENT
            ).apply { marginEnd = 16 }

            addView(android.view.View(activity).apply {
                layoutParams = LinearLayout.LayoutParams(20, 20).apply { topMargin = 28 }
                background = android.graphics.drawable.GradientDrawable().apply {
                    shape = android.graphics.drawable.GradientDrawable.OVAL
                    setColor("#4CAF50".toColorInt())
                }
            })

            addView(android.view.View(activity).apply {
                layoutParams = LinearLayout.LayoutParams(3, 0, 1f).apply {
                    topMargin = 4
                    bottomMargin = 4
                }
                setBackgroundColor(if (isDark) "#5F6368".toColorInt() else "#DADCE0".toColorInt())
            })

            addView(android.view.View(activity).apply {
                layoutParams = LinearLayout.LayoutParams(20, 20).apply { bottomMargin = 28 }
                background = android.graphics.drawable.GradientDrawable().apply {
                    shape = android.graphics.drawable.GradientDrawable.OVAL
                    setColor("#2563EB".toColorInt())
                }
            })
        }
    }

    /**
     * Builds a labeled row with a colored dot indicator, used in navigation panels.
     *
     * @param label the text to display (e.g., a room name or "Your location")
     * @param dotColor the color of the circle indicator next to the label
     * @return a [LinearLayout] containing the dot and label
     */
    private fun buildField(label: String, dotColor: Int): LinearLayout {
        return LinearLayout(activity).apply {
            orientation = LinearLayout.HORIZONTAL
            gravity = Gravity.CENTER_VERTICAL
            setPadding(16, 20, 16, 20)

            addView(android.view.View(activity).apply {
                layoutParams = LinearLayout.LayoutParams(24, 24).apply {
                    marginEnd = 20
                }
                background = android.graphics.drawable.GradientDrawable().apply {
                    shape = android.graphics.drawable.GradientDrawable.OVAL
                    setColor(dotColor)
                }
            })

            addView(TextView(activity).apply {
                text = label
                textSize = 16f
                setTextColor(this@NavigationManager.textColor)
                layoutParams = LinearLayout.LayoutParams(
                    0, ViewGroup.LayoutParams.WRAP_CONTENT, 1f
                )
            })
        }
    }

    /**
     * Removes the route plan panel from the UI if it is currently showing.
     */
    fun dismissPlanPanel() {
        navigationPlanPanel?.let { container.removeView(it) }
        navigationPlanPanel = null
    }

    /**
     * Shows the navigation plan panel, either with a pre-selected destination or with
     * an interactive destination picker.
     *
     * If a [destination] is provided, directions are fetched immediately and the plan
     * panel is displayed with route details. If [destination] is `null`, a picker panel
     * with origin and destination input fields is shown instead.
     *
     * @param destination the target [Space], or `null` to show the destination picker
     * @param userLat the user's current latitude, or `null` if unavailable
     * @param userLon the user's current longitude, or `null` if unavailable
     * @param floorId the user's current Mappedin floor ID, or `null` if unavailable
     * @param accessible whether to request accessible-only routes
     */
    fun showNavigationPlanPanel(
        destination: Space?,
        userLat: Double?,
        userLon: Double?,
        floorId: String?,
        accessible: Boolean
    ) {
        dismissInfoPanel()
        dismissNavigationPanel()
        dismissPlanPanel()

        if (destination != null) {
            // Already have a destination — fetch route and show
            fetchAndShowPlan(destination, userLat, userLon, floorId, accessible)
        } else {
            // No destination yet — show panel with destination picker
            buildPlanPanelWithPicker(userLat, userLon, floorId, accessible)
        }
    }

    /**
     * Builds and displays a plan panel with interactive origin and destination input fields.
     *
     * Allows the user to search for and select origin and destination spaces from the
     * full list of available rooms. When both fields are filled, directions are fetched
     * automatically via [tryFetchRoute]. Includes a swap button to reverse the fields.
     *
     * @param userLat the user's current latitude, or `null` if unavailable
     * @param userLon the user's current longitude, or `null` if unavailable
     * @param floorId the user's current Mappedin floor ID, or `null` if unavailable
     * @param accessible whether to request accessible-only routes
     */
    private fun buildPlanPanelWithPicker(
        userLat: Double?,
        userLon: Double?,
        floorId: String?,
        accessible: Boolean
    ) {
        selectedOrigin = null
        selectedDestination = null

        val filteredNames = mutableListOf<String>()
        val adapter = SearchResultAdapter(activity, filteredNames, isDark)

        val inputBg = if (isDark) "#303134".toColorInt() else "#F1F3F4".toColorInt()
        val inputText = if (isDark) "#E8EAED".toColorInt() else "#202124".toColorInt()
        val inputHint = if (isDark) "#9AA0A6".toColorInt() else "#5F6368".toColorInt()

        lateinit var originInput: android.widget.EditText
        lateinit var destInput: android.widget.EditText
        lateinit var resultsList: ListView

        originInput = android.widget.EditText(activity).apply {
            hint = "Your location"
            setText("Your location")
            textSize = 15f
            setTextColor(inputText)
            setHintTextColor(inputHint)
            isSingleLine = true
            background = android.graphics.drawable.GradientDrawable().apply {
                cornerRadius = 24f
                setColor(inputBg)
            }
            setPadding(36, 20, 36, 20)
            layoutParams = LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.WRAP_CONTENT
            )
            setOnFocusChangeListener { _, hasFocus ->
                if (hasFocus) {
                    activeField = "origin"
                    setText("")
                }
            }
        }

        destInput = android.widget.EditText(activity).apply {
            hint = "Choose destination"
            textSize = 15f
            setTextColor(inputText)
            setHintTextColor(inputHint)
            isSingleLine = true
            background = android.graphics.drawable.GradientDrawable().apply {
                cornerRadius = 24f
                setColor(inputBg)
            }
            setPadding(36, 20, 36, 20)
            layoutParams = LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.WRAP_CONTENT
            )
            setOnFocusChangeListener { _, hasFocus ->
                if (hasFocus) activeField = "destination"
            }
        }

        val watcher = object : android.text.TextWatcher {
            override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {}
            override fun afterTextChanged(s: android.text.Editable?) {}
            override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {
                val q = s?.toString()?.trim()?.lowercase() ?: ""
                filteredNames.clear()
                if (q.isNotBlank() && q != "your location") {
                    filteredNames.addAll(
                        activity.allSpaces.map { it.name }
                            .filter { it.isNotBlank() && it.lowercase().contains(q) }
                            .distinct()
                            .sorted()
                            .take(8)
                    )
                }
                adapter.notifyDataSetChanged()
                resultsList.visibility =
                    if (filteredNames.isEmpty()) android.view.View.GONE
                    else android.view.View.VISIBLE
            }
        }
        originInput.addTextChangedListener(watcher)
        destInput.addTextChangedListener(watcher)

        navigationPlanPanel = LinearLayout(activity).apply {
            orientation = LinearLayout.VERTICAL
            setPadding(0, 0, 0, 0)
            elevation = 24f
            background = android.graphics.drawable.GradientDrawable().apply {
                cornerRadii = floatArrayOf(32f, 32f, 32f, 32f, 0f, 0f, 0f, 0f)
                setColor(bgColor)
            }

            // Fields row
            val fieldsRow = LinearLayout(activity).apply {
                orientation = LinearLayout.HORIZONTAL
                gravity = Gravity.CENTER_VERTICAL
                setPadding(24, 32, 16, 16)

                addView(buildDotsColumn())

                val inputsColumn = LinearLayout(activity).apply {
                    orientation = LinearLayout.VERTICAL
                    layoutParams = LinearLayout.LayoutParams(0, ViewGroup.LayoutParams.WRAP_CONTENT, 1f)
                }

                inputsColumn.addView(originInput)
                inputsColumn.addView(android.view.View(activity).apply {
                    layoutParams = LinearLayout.LayoutParams(
                        ViewGroup.LayoutParams.MATCH_PARENT, 12
                    )
                })
                inputsColumn.addView(destInput)

                addView(inputsColumn)

                addView(Button(activity).apply {
                    text = "⇅"
                    textSize = 20f
                    setTextColor(this@NavigationManager.textColor)
                    setBackgroundColor(android.graphics.Color.TRANSPARENT)
                    layoutParams = LinearLayout.LayoutParams(
                        ViewGroup.LayoutParams.WRAP_CONTENT,
                        ViewGroup.LayoutParams.MATCH_PARENT
                    ).apply { marginStart = 8 }
                    setOnClickListener {
                        val tempSpace = selectedOrigin
                        selectedOrigin = selectedDestination
                        selectedDestination = tempSpace

                        val tempText = originInput.text.toString()
                        originInput.setText(destInput.text.toString())
                        destInput.setText(
                            if (tempText == "Your location" || tempText.isBlank()) ""
                            else tempText
                        )
                        if (selectedOrigin == null) originInput.setText("Your location")
                    }
                })
            }
            addView(fieldsRow)

            resultsList = ListView(activity).apply {
                visibility = android.view.View.GONE
                val bg = if (isDark) "#303134".toColorInt() else "#FFFFFF".toColorInt()
                divider = null
                dividerHeight = 0
                background = android.graphics.drawable.GradientDrawable().apply {
                    cornerRadius = 16f
                    setColor(bg)
                }
                layoutParams = LinearLayout.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT, 600
                ).apply {
                    marginStart = 24
                    marginEnd = 24
                }
            }
            resultsList.adapter = adapter
            resultsList.setOnItemClickListener { _, _, position, _ ->
                val selectedName = filteredNames[position]
                val selectedSpace = activity.allSpaces.find { it.name == selectedName }
                if (selectedSpace != null) {
                    if (activeField == "origin") {
                        selectedOrigin = selectedSpace
                        originInput.setText(selectedName)
                        originInput.clearFocus()
                        destInput.requestFocus()
                    } else {
                        selectedDestination = selectedSpace
                        destInput.setText(selectedName)
                        destInput.clearFocus()
                    }
                    filteredNames.clear()
                    adapter.notifyDataSetChanged()
                    resultsList.visibility = android.view.View.GONE
                    tryFetchRoute(userLat, userLon, floorId, accessible)
                }
            }
            addView(resultsList)

            addView(Button(activity).apply {
                text = "Close"
                isAllCaps = false
                setTextColor(this@NavigationManager.textColor)
                setBackgroundColor(android.graphics.Color.TRANSPARENT)
                layoutParams = LinearLayout.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.WRAP_CONTENT
                ).apply {
                    topMargin = 8
                    bottomMargin = 8
                }
                setOnClickListener { dismissPlanPanel() }
            })
        }

        val params = FrameLayout.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT,
            ViewGroup.LayoutParams.WRAP_CONTENT
        ).apply {
            gravity = Gravity.BOTTOM
            bottomMargin = 180
        }
        container.addView(navigationPlanPanel, params)
    }

    /**
     * Attempts to fetch directions once both origin and destination have been selected.
     *
     * If a [selectedOrigin] space is set, a space-to-space route is calculated. Otherwise,
     * the user's current coordinate (from [userLat], [userLon], [floorId]) is used as the
     * origin. On success, the plan panel is replaced with route details.
     *
     * @param userLat the user's current latitude, or `null` if unavailable
     * @param userLon the user's current longitude, or `null` if unavailable
     * @param floorId the user's current Mappedin floor ID, or `null` if unavailable
     * @param accessible whether to request accessible-only routes
     */
    private fun tryFetchRoute(
        userLat: Double?,
        userLon: Double?,
        floorId: String?,
        accessible: Boolean
    ) {
        val dest = selectedDestination ?: return

        val origin: NavigationTarget = if (selectedOrigin != null) {
            NavigationTarget.SpaceTarget(selectedOrigin!!)
        } else {
            if (userLat == null || userLon == null || floorId == null) {
                android.widget.Toast.makeText(activity, "Waiting for location...", android.widget.Toast.LENGTH_SHORT).show()
                return
            }
            NavigationTarget.CoordinateTarget(Coordinate(userLat, userLon, floorId))
        }

        val options = GetDirectionsOptions(accessible = accessible)

        mapView.mapData.getDirections(origin, NavigationTarget.SpaceTarget(dest), options) { result ->
            result.onSuccess { directions ->
                if (directions != null) {
                    activity.runOnUiThread {
                        dismissPlanPanel()
                        buildPlanPanel(
                            dest, directions,
                            userLat ?: 0.0, userLon ?: 0.0,
                            floorId ?: "", accessible
                        )
                    }
                }
            }
            result.onFailure {
                activity.runOnUiThread {
                    android.widget.Toast.makeText(activity, "No route found", android.widget.Toast.LENGTH_SHORT).show()
                }
            }
        }
    }

    /**
     * Fetches directions from the user's current position to a destination and displays
     * the route plan panel.
     *
     * @param destination the target [Space]
     * @param userLat the user's current latitude, or `null` if unavailable
     * @param userLon the user's current longitude, or `null` if unavailable
     * @param floorId the user's current Mappedin floor ID, or `null` if unavailable
     * @param accessible whether to request accessible-only routes
     */
    private fun fetchAndShowPlan(
        destination: Space,
        userLat: Double?,
        userLon: Double?,
        floorId: String?,
        accessible: Boolean
    ) {
        if (userLat == null || userLon == null || floorId == null) {
            activity.runOnUiThread {
                android.widget.Toast.makeText(activity, "Waiting for location...", android.widget.Toast.LENGTH_SHORT).show()
            }
            return
        }

        val origin = NavigationTarget.CoordinateTarget(
            Coordinate(userLat, userLon, floorId)
        )

        val options = GetDirectionsOptions(accessible = accessible)

        mapView.mapData.getDirections(origin, NavigationTarget.SpaceTarget(destination), options) { result ->
            result.onSuccess { directions ->
                if (directions == null) {
                    activity.runOnUiThread {
                        android.widget.Toast.makeText(activity, "No route found", android.widget.Toast.LENGTH_SHORT).show()
                    }
                    return@onSuccess
                }

                activity.runOnUiThread {
                    buildPlanPanel(destination, directions, userLat, userLon, floorId, accessible)
                }
            }

            result.onFailure {
                activity.runOnUiThread {
                    android.widget.Toast.makeText(activity, "Could not find route", android.widget.Toast.LENGTH_SHORT).show()
                }
            }
        }
    }

    /**
     * Starts live turn-by-turn navigation from the user's current location to a destination.
     *
     * Fetches directions using the user's coordinate as origin, draws the navigation path
     * on the map with animated arrows, adds instruction markers at each waypoint, and
     * displays the active navigation panel with step-by-step instructions.
     *
     * If the initial coordinate-based route fails, falls back to [fallbackNavigate] which
     * uses the nearest space on the user's floor as a proxy origin.
     *
     * @param destination the target [Space] to navigate to
     * @param userLat the user's current latitude
     * @param userLon the user's current longitude
     * @param floorId the Mappedin floor ID of the user's current floor
     * @param accessible whether to request accessible-only routes (defaults to `false`)
     */
    fun navigateTo(destination: Space, userLat: Double, userLon: Double, floorId: String, accessible: Boolean = false) {
        dismissInfoPanel()

        val origin = NavigationTarget.CoordinateTarget(
            Coordinate(userLat, userLon, floorId)
        )
        useAccessible = accessible
        val options = GetDirectionsOptions(accessible = accessible)

        mapView.mapData.getDirections(origin, NavigationTarget.SpaceTarget(destination), options) { result ->
            result.onSuccess { directions ->
                if (directions != null) {
                    currentDirections = directions
                    activeDestination = destination
                    activeFloorId = floorId
                    isNavigating = true

                    mapView.navigation.draw(directions, navOptions) { drawResult ->
                        drawResult.onSuccess {
                            addInstructionMarkers(directions, destination.name)
                            activity.runOnUiThread {
                                showNavigationPanel(destination, directions)
                            }
                        }
                    }

                } else {
                    fallbackNavigate(destination, userLat, userLon, floorId)
                }
            }
            result.onFailure {
                fallbackNavigate(destination, userLat, userLon, floorId)
            }
        }
    }

    /**
     * Attempts navigation using the nearest space on the user's floor as a proxy origin.
     *
     * This is used as a fallback when coordinate-based direction calculation fails,
     * typically because the user's exact position does not map to a navigable area.
     * Finds the closest [Space] on the same floor by Euclidean distance and routes from
     * that space to the destination.
     *
     * @param destination the target [Space] to navigate to
     * @param userLat the user's current latitude
     * @param userLon the user's current longitude
     * @param floorId the Mappedin floor ID of the user's current floor
     */
    private fun fallbackNavigate(destination: Space, userLat: Double, userLon: Double, floorId: String) {

        val nearestSpace = activity.allSpaces
            .filter { it.floor == floorId }
            .minByOrNull { space ->
                val dLat = (space.center?.latitude ?: 0.0) - userLat
                val dLon = (space.center?.longitude ?: 0.0) - userLon
                dLat * dLat + dLon * dLon
            }

        if (nearestSpace == null) {
            Log.e("Navigation", "No space found on floor $floorId")
            activity.runOnUiThread {
                android.widget.Toast.makeText(activity, "No route found", android.widget.Toast.LENGTH_SHORT).show()
            }
            return
        }

        Log.d("Navigation", "Fallback using space: '${nearestSpace.name}' id=${nearestSpace.id}")

        val options = GetDirectionsOptions(accessible = useAccessible)
        mapView.mapData.getDirections(
            NavigationTarget.SpaceTarget(nearestSpace),
            NavigationTarget.SpaceTarget(destination),
            options
        ) { result ->
            result.onSuccess { directions ->
                if (directions != null) {
                    drawNavigation(destination, directions)
                } else {
                    activity.runOnUiThread {
                        android.widget.Toast.makeText(activity, "No route found to ${destination.name}", android.widget.Toast.LENGTH_SHORT).show()
                    }
                }
            }
            result.onFailure {
                Log.e("Navigation", "Fallback also failed", it)
            }
        }
    }

    /**
     * Draws a navigation route on the map and displays the navigation panel.
     *
     * Clears any existing paths and markers, then renders the new route with animated
     * arrows and instruction markers. Sets the navigation state to active.
     *
     * @param destination the target [Space]
     * @param directions the calculated [Directions] to render
     */
    private fun drawNavigation(destination: Space, directions: Directions) {
        mapView.navigation.clear()
        mapView.paths.removeAll()
        mapView.markers.removeAll()

        mapView.navigation.draw(directions, navOptions) { drawResult ->
            drawResult.onSuccess {
                activeDestination = destination
                currentDirections = directions
                isNavigating = true
                addInstructionMarkers(directions, destination.name)
                activity.runOnUiThread {
                    showNavigationPanel(destination, directions)
                }
            }
        }
    }

    /**
     * Displays the active navigation bottom panel with turn-by-turn instructions.
     *
     * Shows the destination name, total distance, numbered step-by-step directions
     * in a scrollable list, and a "Stop Navigation" button. Each step is formatted
     * by [formatInstruction] into human-readable text.
     *
     * @param destination the [Space] being navigated to
     * @param directions the [Directions] containing instructions and distance
     */
    private fun showNavigationPanel(destination: Space, directions: Directions) {
        dismissNavigationPanel()

        val distanceText = if (directions.distance < 1000) "${directions.distance.toInt()}m"
        else "${"%.1f".format(directions.distance / 1000)}km"

        navigationPanel = LinearLayout(activity).apply {
            orientation = LinearLayout.VERTICAL
            setPadding(48, 36, 48, 36)
            elevation = 24f
            background = android.graphics.drawable.GradientDrawable().apply {
                cornerRadii = floatArrayOf(32f, 32f, 32f, 32f, 0f, 0f, 0f, 0f)
                setColor(bgColor)
            }

            // Title
            addView(TextView(activity).apply {
                text = "Navigating to ${destination.name}"
                setTextColor(this@NavigationManager.textColor)
                textSize = 18f
                setTypeface(null, android.graphics.Typeface.BOLD)
            })

            // Distance
            addView(TextView(activity).apply {
                text = distanceText
                setTextColor(if (isDark) "#AAAAAA".toColorInt() else "#666666".toColorInt())
                textSize = 14f
                layoutParams = LinearLayout.LayoutParams(
                    ViewGroup.LayoutParams.WRAP_CONTENT,
                    ViewGroup.LayoutParams.WRAP_CONTENT
                ).apply { topMargin = 8 }
            })

            // Turn-by-turn instructions
            val instructions = directions.instructions
            if (instructions.isNotEmpty()) {
                val scrollView = android.widget.ScrollView(activity).apply {
                    layoutParams = LinearLayout.LayoutParams(
                        ViewGroup.LayoutParams.MATCH_PARENT,
                        400  // max height for the instruction list
                    ).apply { topMargin = 16 }
                }

                val stepsColumn = LinearLayout(activity).apply {
                    orientation = LinearLayout.VERTICAL
                    setPadding(0, 8, 0, 8)
                }

                for (i in instructions.indices) {
                    val instruction = instructions[i]
                    val isLast = i == instructions.size - 1
                    val nextInstruction = if (!isLast) instructions[i + 1] else null

                    val stepText = if (isLast) {
                        "Arrive at ${destination.name}"
                    } else {
                        formatInstruction(instruction, nextInstruction, isLast, destination.name)
                    }

                    stepsColumn.addView(LinearLayout(activity).apply {
                        orientation = LinearLayout.HORIZONTAL
                        gravity = android.view.Gravity.CENTER_VERTICAL
                        setPadding(0, 16, 0, 16)

                        // Step number circle
                        addView(TextView(activity).apply {
                            text = "${i + 1}"
                            textSize = 13f
                            gravity = android.view.Gravity.CENTER
                            setTextColor(android.graphics.Color.WHITE)
                            background = android.graphics.drawable.GradientDrawable().apply {
                                shape = android.graphics.drawable.GradientDrawable.OVAL
                                setColor("#2563EB".toColorInt())
                                setSize(64, 64)
                            }
                            layoutParams = LinearLayout.LayoutParams(64, 64).apply {
                                marginEnd = 20
                            }
                        })

                        // Step text
                        addView(TextView(activity).apply {
                            text = stepText
                            textSize = 14f
                            setTextColor(this@NavigationManager.textColor)
                            layoutParams = LinearLayout.LayoutParams(
                                0, ViewGroup.LayoutParams.WRAP_CONTENT, 1f
                            )
                        })
                    })

                    // Divider between steps
                    if (!isLast) {
                        stepsColumn.addView(android.view.View(activity).apply {
                            setBackgroundColor(
                                if (isDark) "#333333".toColorInt() else "#E0E0E0".toColorInt()
                            )
                            layoutParams = LinearLayout.LayoutParams(
                                ViewGroup.LayoutParams.MATCH_PARENT, 1
                            ).apply { marginStart = 84 }
                        })
                    }
                }

                scrollView.addView(stepsColumn)
                addView(scrollView)
            }

            // Stop button
            addView(Button(activity).apply {
                text = "Stop Navigation"
                isAllCaps = false
                setTextColor(android.graphics.Color.WHITE)
                background = android.graphics.drawable.GradientDrawable().apply {
                    cornerRadius = 24f
                    setColor("#DC2626".toColorInt())
                }
                layoutParams = LinearLayout.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.WRAP_CONTENT
                ).apply { topMargin = 24 }
                setOnClickListener { stopNavigation() }
            })
        }

        val params = FrameLayout.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT,
            ViewGroup.LayoutParams.WRAP_CONTENT
        ).apply {
            gravity = Gravity.BOTTOM
            bottomMargin = 180
        }
        container.addView(navigationPanel, params)
    }

    /**
     * Calculates and displays a route between two selected spaces.
     *
     * Unlike [navigateTo], this method uses a space (not a coordinate) as the origin.
     * Draws the route with animated arrows, adds instruction markers, switches the map
     * to the origin's floor, and displays the navigation panel.
     *
     * @param origin the starting [Space]
     * @param destination the target [Space]
     * @param accessible whether to request accessible-only routes (defaults to `false`)
     */
    fun navigateFromSpace(origin: Space, destination: Space, accessible: Boolean = false) {
        dismissInfoPanel()
        useAccessible = accessible
        val options = GetDirectionsOptions(accessible = accessible)

        mapView.mapData.getDirections(
            NavigationTarget.SpaceTarget(origin),
            NavigationTarget.SpaceTarget(destination),
            options
        ) { result ->
            result.onSuccess { directions ->
                if (directions != null) {
                    currentDirections = directions
                    activeDestination = destination
                    isNavigating = true
                    mapView.navigation.draw(directions, navOptions) { drawResult ->
                        drawResult.onSuccess {
                            addInstructionMarkers(directions, destination.name)
                            activity.runOnUiThread {
                                showNavigationPanel(destination, directions)
                            }
                        }
                    }
                }
            }
        }
    }


    /**
     * Removes the active navigation panel from the UI.
     */
    private fun dismissNavigationPanel() {
        navigationPanel?.let { container.removeView(it) }
        navigationPanel = null
    }

    /**
     * Stops all active navigation and clears the map.
     *
     * Clears the navigation path, removes all markers and drawn paths, resets navigation
     * state flags, and dismisses both the navigation panel and plan panel.
     */
    fun stopNavigation() {
        mapView.navigation.clear()
        mapView.markers.removeAll()
        mapView.paths.removeAll()
        isNavigating = false
        dismissNavigationPanel()
        dismissPlanPanel()
        activeDestination = null
        currentDirections = null
    }

    /**
     * Marks a destination as the active navigation target and sets the navigating flag.
     *
     * Used to transition into live navigation mode after a route has been drawn.
     *
     * @param destination the [Space] being navigated to
     */
    fun startLiveNavigation(destination: Space) {
        activeDestination = destination
        isNavigating = true
    }



    /**
     * Updates the navigation path highlight to reflect the user's current position.
     *
     * Highlights the portion of the path from the route start to the user's current
     * coordinate in grey, visually indicating progress along the route. Called by
     * [MapActivity.onLocationChanged] during active navigation.
     *
     * @param userLat the user's current latitude
     * @param userLon the user's current longitude
     * @param floorId the Mappedin floor ID of the user's current floor
     */
    fun updateNavigationPath(userLat: Double, userLon: Double, floorId: String) {
        val dest = activeDestination ?: return
        if (!isNavigating) return
        val directions = currentDirections ?: return

        val coordinate = mapView.createCoordinate(
            userLat,
            userLon,
            floorId
        )

        directions.coordinates.firstOrNull()?.let { firstCoordinate ->
            mapView.navigation.highlightPathSection(
                from = firstCoordinate,
                to = coordinate,
                options = PathSectionHighlightOptions(
                    animationDuration = 0,
                    color = "#9d9d9d",
                    widthMultiplier = 1.1
                )
            )
        }
    }

    /**
     * Places HTML marker bubbles at each instruction waypoint along the navigation route.
     *
     * Each marker displays a numbered step with a human-readable instruction (e.g.,
     * "1. Turn left and go 15 meters"). The final marker is styled green and reads
     * "Arrive at [destination]". Markers are set to [CollisionRankingTier.ALWAYS_VISIBLE].
     *
     * @param directions the [Directions] containing the list of instructions
     * @param destinationName the display name of the destination for the arrival marker
     */
    private fun addInstructionMarkers(directions: Directions, destinationName: String) {
        val instructions = directions.instructions

        for (i in instructions.indices) {
            val instruction = instructions[i]
            val nextInstruction = if (i < instructions.size - 1) instructions[i + 1] else null
            val isLast = i == instructions.size - 1
            val distance = nextInstruction?.distance?.toInt() ?: 0

            // Skip non-last instructions with no distance
            if (!isLast && distance <= 0) continue

            val markerText = formatInstruction(instruction, nextInstruction, isLast, destinationName)

            val bgColor = if (isLast) "#358320" else "#002F6C"

            val markerTemplate = """
            <div style="
                background: $bgColor;
                color: white;
                padding: 4px 10px;
                border-radius: 16px;
                font-family: -apple-system, sans-serif;
                font-size: 10px;
                white-space: nowrap;
                box-shadow: 0 2px 8px rgba(0,0,0,0.2);
            ">
                <span>${i + 1}. $markerText</span>
            </div>
        """.trimIndent()

            mapView.markers.add(
                instruction.coordinate,
                markerTemplate,
                AddMarkerOptions(
                    rank = AddMarkerOptions.Rank.Tier(CollisionRankingTier.ALWAYS_VISIBLE),
                ),
            ) { }
        }
    }

    /**
     * Converts a [DirectionInstruction][com.mappedin.models.DirectionInstruction] into
     * a human-readable text string for display in markers and the navigation panel.
     *
     * Handles action types including turns (with bearing), connection transitions
     * (stairs, elevators), departures, and straight segments. Appends distance in
     * meters when available from the next instruction.
     *
     * @param instruction the current direction instruction
     * @param nextInstruction the following instruction (used to determine distance), or `null`
     * @param isLast whether this is the final instruction (arrival)
     * @param destinationName the destination name, used for the arrival message
     * @return a formatted instruction string (e.g., "Turn left and go 15 meters")
     */
    private fun formatInstruction(
        instruction: com.mappedin.models.DirectionInstruction,
        nextInstruction: com.mappedin.models.DirectionInstruction?,
        isLast: Boolean,
        destinationName: String
    ): String {
        if (isLast) return "Arrive at $destinationName"

        val action = instruction.action.type?.toString() ?: ""
        val bearing = instruction.action.bearing?.toString() ?: ""
        val connectionType = instruction.action.connectionType?.toString() ?: ""
        val direction = instruction.action.direction?.toString() ?: ""
        val distance = nextInstruction?.distance?.toInt() ?: 0

        val actionText = when {
            // Connections with specific type
            action.equals("TAKE_CONNECTION", ignoreCase = true) && connectionType.contains("ELEVATOR", ignoreCase = true) ->
                "Take the elevator ${direction.lowercase()}"
            action.equals("TAKE_CONNECTION", ignoreCase = true) && connectionType.contains("STAIRS", ignoreCase = true) ->
                "Take the stairs ${direction.lowercase()}"
            action.equals("TAKE_CONNECTION", ignoreCase = true) ->
                "Take the connection ${direction.lowercase()}"
            action.equals("EXIT_CONNECTION", ignoreCase = true) && connectionType.contains("ELEVATOR", ignoreCase = true) ->
                "Exit the elevator"
            action.equals("EXIT_CONNECTION", ignoreCase = true) && connectionType.contains("STAIRS", ignoreCase = true) ->
                "Exit the stairs"
            action.equals("EXIT_CONNECTION", ignoreCase = true) ->
                "Exit and continue"

            // Turns
            action.equals("TURN", ignoreCase = true) -> when {
                bearing.equals("LEFT", ignoreCase = true) -> "Turn left"
                bearing.equals("RIGHT", ignoreCase = true) -> "Turn right"
                bearing.equals("SLIGHT_LEFT", ignoreCase = true) -> "Turn slight left"
                bearing.equals("SLIGHT_RIGHT", ignoreCase = true) -> "Turn slight right"
                bearing.equals("BEAR_LEFT", ignoreCase = true) -> "Bear left"
                bearing.equals("BEAR_RIGHT", ignoreCase = true) -> "Bear right"
                else -> "Turn $bearing".lowercase().replaceFirstChar { it.uppercase() }
            }

            // Departure
            action.equals("DEPARTURE", ignoreCase = true) -> "Depart"

            // Straight
            action.equals("STRAIGHT", ignoreCase = true) -> "Continue straight"

            // Fallback
            else -> action.replace("_", " ").lowercase().replaceFirstChar { it.uppercase() }
        }

        return if (distance > 0) "$actionText and go $distance meters" else actionText
    }

    /**
     * Recalculates the navigation route from the user's current position to the active destination.
     *
     * Used when the user has deviated from the original route. Guards against concurrent
     * reroute requests with the [isRerouting] flag. On success, updates [currentDirections]
     * and redraws the navigation path on the map.
     *
     * @param destination the [Space] the user is navigating to
     * @param userLat the user's current latitude
     * @param userLon the user's current longitude
     * @param floorId the Mappedin floor ID of the user's current floor
     */
    private fun rerouteToDestination(destination: Space, userLat: Double, userLon: Double, floorId: String) {
        if (isRerouting) return
        isRerouting = true

        val origin = NavigationTarget.CoordinateTarget(
            Coordinate(userLat, userLon, floorId)
        )

        val options = GetDirectionsOptions(accessible = useAccessible)
        mapView.mapData.getDirections(origin, NavigationTarget.SpaceTarget(destination)) { result ->
            isRerouting = false

            result.onSuccess { directions ->
                if (directions != null) {
                    currentDirections = directions
                    activeFloorId = floorId
                    mapView.navigation.draw(directions) { }
                }
            }
        }
    }

    /**
     * Returns whether the space info panel is currently visible.
     *
     * @return `true` if the info panel is showing, `false` otherwise
     */
    fun isInfoPanelShowing(): Boolean {
        // return whether info panel view is visible
        return infoPanel?.visibility == View.VISIBLE
    }

}