package com.teamrocket.uttylermaps.activities


/*
    parts  of the code in this project are adapted from
    Mappedin's android sdk documentation at https://developer.mappedin.com/android-sdk

    All dokka Kdot comments below are generated by Claude. Prompt: Add dokka kdoc comments
    to the class and each function
 */

